from __future__ import annotations

import re

MEETING_URL_TERMS = {
    "meeting",
    "meetings",
    "find-a-meeting",
    "find-meeting",
    "find-meeting/find-a-meeting",
    "meeting-schedule",
    "meetings-schedule",
    "schedule",
    "where-to-find",
    "locator",
    "location",
    "locations",
    "meeting-locations",
    "group",
    "groups",
    "aa-groups",
    "a-a-groups",
    "alcoholics-anonymous-groups",
    "tsml-",
    "reuniao",
    "reunioes",
    "reunião",
    "reuniões",
    "reunion",
    "reunions",
    "réunion",
    "réunions",
    "reuniones",
    "horario",
    "horarios",
    "horário",
    "horários",
    "calendario",
    "calendário",
    "spotkania",
    "spotkanie",
    "mityng",
    "mityngi",
    "miting",
    "mitingi",
    "møder",
    "moder",
    "møde",
    "mode",
    "moten",
    "möten",
    "mote",
    "möte",
    "moeten",
    "bijeenkomst",
    "bijeenkomsten",
    "treffen",
    "meetingsuche",
    "συναντήσεις",
    "συναντηση",
    "synantiseis",
    "synantisi",
    "встречи",
    "vstrechi",
    "การประชุม",
    "ประชุม",
    "pertemuan",
    "mesyuarat",
}

MEETING_TEXT_TERMS = {
    "meeting list",
    "meeting schedule",
    "find a meeting",
    "find meeting",
    "find an online meeting",
    "find a face-to-face meeting",
    "meeting finder",
    "meeting locations",
    "group finder",
    "aa groups",
    "a.a. groups",
    "alcoholics anonymous groups",
    "search meetings",
    "view all meetings",
    "online meetings",
    "in-person",
    "presencial",
    "encontrar reunião",
    "encontrar reuniao",
    "procurar reunião",
    "procurar reuniao",
    "buscar reunión",
    "buscar reunion",
    "horário das reuniões",
    "horario das reunioes",
    "horario de reuniones",
    "trouver une réunion",
    "trouver une reunion",
    "réunions en ligne",
    "liste des réunions",
    "srečanja",
    "srecanja",
    "srečanje",
    "srecanje",
    "spotkania",
    "lista spotkań",
    "harmonogram spotkań",
    "mityngi",
    "mitingi",
    "find møde",
    "mødeliste",
    "mødeoversigt",
    "hitta möte",
    "möteslista",
    "finn møte",
    "møteliste",
    "vergaderingen",
    "bijeenkomsten",
    "meeting zoeken",
    "treffen finden",
    "meetingliste",
    "συναντήσεις",
    "αναζήτηση συνάντησης",
    "встречи",
    "найти встречу",
    "jadual mesyuarat",
    "cari mesyuarat",
    "jadwal pertemuan",
    "cari pertemuan",
    "ค้นหาการประชุม",
}

WEEKDAY_TERMS = {
    "today",
    "sunday",
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sun",
    "mon",
    "tue",
    "tues",
    "wed",
    "thu",
    "thur",
    "thurs",
    "fri",
    "sat",
    "domingo",
    "segunda",
    "segunda-feira",
    "terça",
    "terca",
    "terça-feira",
    "terca-feira",
    "quarta",
    "quarta-feira",
    "quinta",
    "quinta-feira",
    "sexta",
    "sexta-feira",
    "sábado",
    "sabado",
    "lunes",
    "martes",
    "miércoles",
    "miercoles",
    "jueves",
    "viernes",
    "dimanche",
    "lundi",
    "mardi",
    "mercredi",
    "jeudi",
    "vendredi",
    "samedi",
    "codziennie",
    "niedziela",
    "poniedziałek",
    "poniedzialek",
    "wtorek",
    "środa",
    "sroda",
    "czwartek",
    "piątek",
    "piatek",
    "sobota",
    "søndag",
    "sondag",
    "mandag",
    "tirsdag",
    "onsdag",
    "torsdag",
    "fredag",
    "lørdag",
    "lordag",
    "söndag",
    "måndag",
    "tisdag",
    "lördag",
    "zondag",
    "maandag",
    "dinsdag",
    "woensdag",
    "donderdag",
    "vrijdag",
    "zaterdag",
    "sonntag",
    "montag",
    "dienstag",
    "mittwoch",
    "donnerstag",
    "freitag",
    "samstag",
    "κυριακή",
    "κυριακη",
    "δευτέρα",
    "δευτερα",
    "τρίτη",
    "τριτη",
    "τετάρτη",
    "τεταρτη",
    "πέμπτη",
    "πεμπτη",
    "παρασκευή",
    "παρασκευη",
    "σάββατο",
    "σαββατο",
    "воскресенье",
    "понедельник",
    "вторник",
    "среда",
    "четверг",
    "пятница",
    "суббота",
    "вс",
    "пн",
    "вт",
    "ср",
    "чт",
    "пт",
    "сб",
    "nedelja",
    "ponedeljek",
    "torek",
    "sreda",
    "četrtek",
    "cetrtek",
    "petek",
    "minggu",
    "senin",
    "selasa",
    "rabu",
    "kamis",
    "jumat",
    "jumaat",
    "sabtu",
    "อาทิตย์",
    "จันทร์",
    "อังคาร",
    "พุธ",
    "พฤหัส",
    "ศุกร์",
    "เสาร์",
}

STRONG_MEETING_PATH_SUFFIXES = {
    "/meetings",
    "/meeting-schedule",
    "/meetings-schedule",
    "/find-a-meeting",
    "/find-meeting",
    "/where-to-find",
    "/reunioes",
    "/reuniões",
    "/reuniones",
    "/reunions",
    "/srecanja",
    "/srečanja",
    "/horario",
    "/horários",
    "/horarios",
    "/spotkania",
    "/mityngi",
    "/mitingi",
    "/møder",
    "/moder",
    "/moten",
    "/möten",
    "/bijeenkomsten",
    "/treffen",
    "/встречи",
}

DAY_RE = re.compile(
    r"\b(?:"
    + "|".join(sorted((re.escape(term) for term in WEEKDAY_TERMS), key=len, reverse=True))
    + r")\b",
    re.IGNORECASE,
)
